# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_delete_subcat_lvl'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCat_lvl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
            ],
        ),
    ]
