# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 06:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_subcat_lvl'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcat_lvl',
            name='parent_cat',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.SubCat_lvl'),
        ),
    ]
