# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 07:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_subcat_lvl_parent_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.SubCat_lvl', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='subcat_lvl',
            name='name',
            field=models.CharField(max_length=24, verbose_name='Наименование категории'),
        ),
        migrations.AlterField(
            model_name='subcat_lvl',
            name='parent_cat',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.SubCat_lvl', verbose_name='Является подкатегорией:'),
        ),
    ]
