# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 08:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20171026_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcat_lvl',
            name='parent_cat',
        ),
        migrations.AddField(
            model_name='category',
            name='parent_cat',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Category', verbose_name='Является подкатегорией:'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Category', verbose_name='Категория'),
        ),
        migrations.DeleteModel(
            name='SubCat_lvl',
        ),
    ]
