# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20171026_2041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='lenght',
            new_name='length',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='product_images'),
        ),
    ]
