# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0003_auto_20171103_1040'),
        ('product', '0011_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_materials',
            field=models.ManyToManyField(to='material.Material'),
        ),
    ]
