# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_product_available_materials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description_short',
        ),
        migrations.AlterField(
            model_name='product',
            name='available_materials',
            field=models.ManyToManyField(blank=True, to='material.Material', verbose_name='Доступные материалы'),
        ),
    ]
