# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20171114_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='materials_deck',
            field=models.ManyToManyField(blank=True, related_name='mat_deck', to='material.Material', verbose_name='Доступные материалы столешницы (ДЛЯ КУХНИ)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='materials_face',
            field=models.ManyToManyField(blank=True, related_name='mat_face', to='material.Material', verbose_name='Доступные материалы фасада (ДЛЯ КУХНИ)'),
        ),
    ]
