# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-01 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0001_initial'),
        ('product', '0018_remove_productimage_is_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fitting_1',
            field=models.ManyToManyField(blank=True, related_name='fit_1', to='fitting.Fitting', verbose_name='Фурнитура_1'),
        ),
    ]
