# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-01 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0003_auto_20171103_1040'),
        ('product', '0020_auto_20171201_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='materials_coat',
            field=models.ManyToManyField(blank=True, related_name='mat_coat', to='material.Material', verbose_name='Доступные материалы обивки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='materials_deck',
            field=models.ManyToManyField(blank=True, related_name='mat_deck', to='material.Material', verbose_name='Доступные материалы столешницы'),
        ),
        migrations.AlterField(
            model_name='product',
            name='materials_face',
            field=models.ManyToManyField(blank=True, related_name='mat_face', to='material.Material', verbose_name='Доступные материалы фасада'),
        ),
        migrations.AlterField(
            model_name='product',
            name='materials_others',
            field=models.ManyToManyField(blank=True, related_name='mat_others', to='material.Material', verbose_name='Доступные материалы прочие'),
        ),
    ]
