# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-01 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_auto_20171201_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fitting_1',
            field=models.ManyToManyField(blank=True, related_name='fit_1', to='fitting.Fitting', verbose_name='Фурнитура_4'),
        ),
    ]
