# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-01 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0001_initial'),
        ('product', '0022_auto_20171201_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fitting_2',
            field=models.ManyToManyField(blank=True, related_name='fit_2', to='fitting.Fitting', verbose_name='Фурнитура_2'),
        ),
        migrations.AddField(
            model_name='product',
            name='fitting_3',
            field=models.ManyToManyField(blank=True, related_name='fit_3', to='fitting.Fitting', verbose_name='Фурнитура_3'),
        ),
        migrations.AddField(
            model_name='product',
            name='fitting_4',
            field=models.ManyToManyField(blank=True, related_name='fit_4', to='fitting.Fitting', verbose_name='Фурнитура_4'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fitting_1',
            field=models.ManyToManyField(blank=True, related_name='fit_1', to='fitting.Fitting', verbose_name='Фурнитура_1'),
        ),
    ]
