# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_auto_20171201_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_stock',
            field=models.BooleanField(default=False, verbose_name='Акция'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_descript',
            field=models.TextField(blank=True, verbose_name='Описание акции'),
        ),
    ]
