# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_auto_20171207_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descript', models.TextField(blank=True, verbose_name='Описание акции')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_stock',
        ),
        migrations.AddField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(default=False, verbose_name='Товар по акции'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_descript',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='product.ProductStock', verbose_name='Акция'),
        ),
    ]
