# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 09:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_auto_20171212_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock_descript',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.ProductStock', verbose_name='Акция'),
        ),
    ]
