# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-20 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_auto_20171220_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='fitting_1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fitting_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fitting_3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fitting_4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='materials_coat',
        ),
        migrations.RemoveField(
            model_name='product',
            name='materials_others',
        ),
        migrations.RemoveField(
            model_name='product',
            name='materials_deck',
        ),
        migrations.AddField(
            model_name='product',
            name='materials_deck',
            field=models.TextField(blank=True, verbose_name='Столешница'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='materials_face',
        ),
        migrations.AddField(
            model_name='product',
            name='materials_face',
            field=models.TextField(blank=True, verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='product',
            name='materials_text',
            field=models.TextField(blank=True, verbose_name='Другие материалы'),
        ),
    ]
