# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 10:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fitting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48, verbose_name='Название предмета')),
                ('fitting_image', models.ImageField(default='default/NO_IMAGE.png', upload_to='fitting_images')),
            ],
            options={
                'verbose_name': 'Предмет фурнитуры',
                'verbose_name_plural': 'Предметы фурнитуры',
            },
        ),
        migrations.CreateModel(
            name='FittingCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, verbose_name='Название категории')),
                ('url_name', models.CharField(blank=True, default='', max_length=40, null=True)),
            ],
            options={
                'verbose_name': 'Категория фурнитуры',
                'verbose_name_plural': 'Категории фурнитуры',
            },
        ),
        migrations.AddField(
            model_name='fitting',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='fitting.FittingCategory', verbose_name='Категория фурнитуры'),
        ),
    ]
