# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_auto_20171103_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='material_image',
            field=models.ImageField(default='default/NO_IMAGE.png', upload_to='material_images'),
        ),
    ]
