# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 06:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio_images')),
                ('is_active', models.BooleanField(default=True)),
                ('is_main', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Изображение товара в портфолио',
                'verbose_name_plural': 'Изображения товара в портфолио',
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, verbose_name='Наименование работы')),
            ],
            options={
                'verbose_name': 'Товар в портфолио',
                'verbose_name_plural': 'Товары в портфолио',
            },
        ),
        migrations.AddField(
            model_name='portfolioimage',
            name='prfol_product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.PortfolioItem'),
        ),
    ]
