# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
