# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfolioitem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='main_image',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.PortfolioImage'),
        ),
    ]
