# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 14:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_portfolioitem_main_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioimage',
            name='is_main',
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='main_image',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.PortfolioImage', verbose_name='Основное изображение'),
        ),
    ]
