# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20171120_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
