# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-01 04:57
from __future__ import unicode_literals

from django.db import migrations, models
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_portfolioitem_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioimage',
            name='image',
            field=models.ImageField(upload_to=portfolio.models.portf_image_upload_path),
        ),
    ]
